---
# tasks file for PeterMosmans.dokuwiki

# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Create /var dirs
  file:
    path: "{{ item }}"
    # state: directory
    mode: u=rwX,g=rwX,o=
    group: "{{ dokuwiki_group }}"
    owner: "{{ dokuwiki_user }}"
    recurse: yes
  loop:
    - "{{ dokuwiki_data }}"
    - "{{ dokuwiki_conf }}"
    - "{{ dokuwiki_bin }}"

- name: Copy conf files
  shell: "mv {{dokuwiki_base}}/conf/* {{dokuwiki_conf}}/"
  args:
    executable: /bin/bash

- name: Copy bin files
  shell: "mv {{dokuwiki_base}}/bin/* {{dokuwiki_bin}}/"
  args:
    executable: /bin/bash

- name: Check data not empty
  find: 
    paths: "{{dokuwiki_data}}"
    file_type: any
  register: dokuwiki_data_dir

- name: Copy data files
  shell: "mv {{dokuwiki_base}}/data/* {{dokuwiki_data}}/"
  args:
    executable: /bin/bash
  when: dokuwiki_data_dir.matched|int == 0

- name: Apply permissions for configuration and data files
  file:
    path: "{{ item }}"
    # state: directory
    mode: u=rwX,g=rwX,o=
    group: "{{ dokuwiki_group }}"
    owner: "{{ dokuwiki_user }}"
    recurse: yes
  loop:
    - "{{ dokuwiki_data }}"
    - "{{ dokuwiki_conf }}"
  tags:
    - permission

- name: Apply and deploy inc templates
  template:
    src: "inc/preload.php"
    dest: "{{dokuwiki_base}}/inc/preload.php"
    mode: u=rwX,g=rwX,o=
    group: "{{ dokuwiki_group }}"
    owner: "{{ dokuwiki_user }}"

- name: Apply and deploy configuration templates
  template:
    src: "{{ item.src }}"
    dest: "{{dokuwiki_conf}}/{{ item.path }}"
    mode: u=rwX,g=rwX,o=
    group: "{{ dokuwiki_group }}"
    owner: "{{ dokuwiki_user }}"
  with_filetree: ../templates/conf/
  when: item.state == 'file'

#- name: Install cron job
#  template:
#    src: cleanup.sh.j2
#    dest: "/etc/cron.daily/cleanup-{{ dokuwiki_name }}"
#    mode: u=rwX,g=rX,o=rX
#    group: root
#    owner: root

- name: Secure configuration
  file:
    path: "{{ dokuwiki_base }}/install.php"
    state: absent

- name: Remove deleted plugins
  file:
    path: "{{ dokuwiki_base }}/lib/plugins/{{ item.name }}"
    state: absent
  with_flattened:
    - "{{ dokuwiki_plugins_remove|default([]) }}"
  tags:
    - plugins
    - upgrade

# install plugins
- include_tasks: download-part.yml
  vars:
    parts_path: "{{ dokuwiki_base }}/lib/plugins"
  loop: "{{dokuwiki_plugins | default([])}}"
  loop_control:
    loop_var: part

# Download and install latest version of templates
- include_tasks: download-part.yml
  vars:
    parts_path: "{{ dokuwiki_base }}/lib/tpl"
  loop: "{{dokuwiki_templates | default([])}}"
  loop_control:
    loop_var: part

- name: Set Dokuwiki page permissions
  file:
    path: "{{ dokuwiki_data }}"
    # state: directory
    mode: u=rwX,g=rwX,o=
    group: "{{ dokuwiki_group }}"
    owner: "{{ dokuwiki_user }}"
    recurse: yes
  tags:
    - permission
    - upgrade

- name: Set Dokuwiki configuration permissions
  file:
    path: "{{ dokuwiki_base }}/{{ item }}"
    # state: directory
    mode: u=rwX,g=rwX,o=
    group: "{{ dokuwiki_group }}"
    owner: "{{ dokuwiki_user }}"
    recurse: yes
  with_items:
    - lib/plugins/
    - lib/tpl
  when: ansible_os_family == 'Debian'
  tags:
    - permission
    - upgrade
