---

- name: Install required packages
  become: yes
  apt:
    name: "{{dokuwiki_required_packages}}"
    state: latest


- name: Make sure Dokuwiki base directory exists (workaround for Ansible bug)
  file:
    path: "{{ dokuwiki_base }}"
    state: directory

- name: Make sure dstr cache exist
  file:
    path: "{{dokuwiki_src_cache}}"
    state: directory

- get_url:
    url: "{{ dokuwiki_source }}"
    dest: "{{dokuwiki_src_cache}}/dokuwiki.tar.gz"
    force: no

- name: Download and extract latest version of Dokuwiki
  unarchive:
    src: "{{dokuwiki_src_cache}}/dokuwiki.tar.gz"
    dest: "{{dokuwiki_base}}"
    remote_src: yes
    extra_opts: ['--strip-components=1']
    group: "{{ dokuwiki_group }}"
    owner: "{{ dokuwiki_user }}"
    mode: u=rwX,g=rwX,o=
